### ISSUE TITLE
`rm -r` should be converted into `rmdir`

### ISSUE THREAD

**Issue by AdamRzepka** [sagiegurari/shell2batch#1]
#### Problem Description

`rm` is converted into `del` which works for files. However, `del /Q directory` removes files inside the `directory`, leaving subdirectories and the `directory` itself in place. In order to remove directory recursively, one needs `rmdir /S`. 

So, the conversion should look like this:
```
rm -> del /Q
rm -r -> rmdir /S /Q
```

**Comment by sagiegurari** [comment]
Thanks. will be handled this week.

**Comment by sagiegurari** [comment]
This should be fixed now. If you need it in cargo-make it will take a bit longer until I release a new version of it since I plan to push there few more items.

**Comment by sagiegurari** [comment]
now that cargo-make 0.14.0 is released, i think this case can also be closed.
