### ISSUE TITLE
@echo off at the beginning

### ISSUE THREAD

**Issue by dataf3l** [sagiegurari/shell2batch#10]
**Features Description**
Every shell program should have @echo off at the beginning of the file

**Describe the solution you'd like**
Add the line

**Comment by dataf3l** [comment]
maybe add it on this line?

https://github.com/sagiegurari/shell2batch/blob/cd19e14fc042ca6de29c05fb83d5335ee8b090f5/src/converter.rs#L257

**Comment by sagiegurari** [comment]
I'm not 100% sure about this. Need to think of it.
but i'm guessing you can hack around it if you must have it using the custom conversion tag
```sh
#provide custom windows command for specific shell command
: # shell2batch: @echo off
```

**Comment by dataf3l** [comment]
I understand if you aren't 100% correct, in my mind, every shell script needs that at the beginning, otherwise it just prints all the commands and that's not a good experience.

**Comment by sagiegurari** [comment]
didn't say I'm not correct, said I'm not sure about your request.

as i see it, that's the default os behavior so don't want to force something else.
in addition, that printout is important for tools like cargo-make.
and i did provide a simple workaround for you.

what I'm thinking is to provide a way to give echo suppression but without backward break

**Comment by roblabla** [comment]
Posix Shells have `set -x` and `set +x` for tracing commands - which is basically the same thing as echo off/echo on. The difference is that on windows, echo on is the default while on linux, echo off is.

Maybe we could have shell2batch convert `set -x` and `set +x` to @echo off/@echo on?

**Comment by sagiegurari** [comment]
cool idea!!

**Comment by sagiegurari** [comment]
implemented in dev branch. i'll publish a new release soon.

**Comment by sagiegurari** [comment]
published
