### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/shell2batch#9]
**Features Description**
It'd be nice if a simple `touch file` would work, creating an empty file, and ideally updating the last access time.

**Describe the solution you'd like**

Here's some arcane commands I found while researching this:

`echo n | copy /-y NUL filename.ext` is an ugly but obvious one-liner to create an empty file if it does not exist.

`copy /b filename.ext +,,` will update the timestamp of a file. The `+,,` flag is documented on the [copy command doc](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490886(v=technet.10)).

**Comment by sagiegurari** [comment]
all for it. you want to submit a PR?

**Comment by roblabla** [comment]
Will do, I'll send one in a day or two, currently don't have access to a windows machine.

**Comment by sagiegurari** [comment]
@roblabla this is now implemented in a dev branch

**Comment by roblabla** [comment]
TYVM! Been a bit busy and haven't had much time to dedicate to this :<.

I'll build cargo-make with this and test it this we.

**Comment by sagiegurari** [comment]
published
